export const theme = [
  {
    backgroundColor: "#EAE7B1",
    divBorderColor: "#3C6255",
    circleBackgroundColor: "#A6BB8D",
    circleHoverBackgroundColor: "#95d2aa",
    circleHoverBorderColor: "#3C6255",
  },
  {
    backgroundColor: "#FFC6D3",
    divBorderColor: "#3A4F7A",
    circleBackgroundColor: "#E98EAD",
    circleHoverBackgroundColor: "#FEA1BF",
    circleHoverBorderColor: "#3A4F7A",
  },
  {
    backgroundColor: "#DEFCF9",
    divBorderColor: "#CCA8E9",
    circleBackgroundColor: "#CADEFC",
    circleHoverBackgroundColor: "#FFFF",
    circleHoverBorderColor: "#CCA8E9",
  },
  {
    backgroundColor: "#FFC3A1",
    divBorderColor: "#A75D5D",
    circleBackgroundColor: "#F0997D",
    circleHoverBackgroundColor: "#eca49c",
    circleHoverBorderColor: "#A75D5D",
  },
  {
    backgroundColor: "#FFBABA",
    divBorderColor: "#7B2869",
    circleBackgroundColor: "#C85C8E",
    circleHoverBackgroundColor: "#ef79b0",
    circleHoverBorderColor: "#7B2869",
  },
  {
    backgroundColor: "#F8EDE3",
    divBorderColor: "#85586F",
    circleBackgroundColor: "#D0B8A8",
    circleHoverBackgroundColor: "#DFD3C3",
    circleHoverBorderColor: "#85586F",
  },
  {
    backgroundColor: "#CBEDD5",
    divBorderColor: "#439A97",
    circleBackgroundColor: "#97DECE",
    circleHoverBackgroundColor: "#8ee9eb",
    circleHoverBorderColor: "#439A97",
  },
  {
    backgroundColor: "#F0E9D2",
    divBorderColor: "#181D31",
    circleBackgroundColor: "#678983",
    circleHoverBackgroundColor: "#E6DDC4",
    circleHoverBorderColor: "#181D31",
  },
  {
    backgroundColor: "#FFFBEB",
    divBorderColor: "#251749",
    circleBackgroundColor: "#495579",
    circleHoverBackgroundColor: "#5d6273",
    circleHoverBorderColor: "#251749",
  },
  {
    backgroundColor: "#F2E5E5",
    divBorderColor: "#2B3A55",
    circleBackgroundColor: "#CE7777",
    circleHoverBackgroundColor: "#E8C4C4",
    circleHoverBorderColor: "#2B3A55",
  },
];